Morgan-Stanley/treadmill-aws

lib/python/treadmill_aws/hostmanager.py

We now render and send userdata to AWS as MIME multipart messages.
render_template can accept K:V pairs and a list of URLs to ingest cloud-init from.

render_template now will insert K:V pairs and can format MIME messages.

---

lib/python/treadmill_aws/cli/admin/aws/image.py
lib/python/treadmill_aws/cli/admin/aws/secgroup.py
lib/python/treadmill_aws/cli/admin/aws/subnet.py
lib/python/treadmill_aws/cli/options.py
tests/cli/options_test.py

- Support custom parsing, which all automatically detect resource id
string based on regex, otherwise construct tags filter.

Refactor how CLI parses aws indentifiers.

---

lib/python/treadmill_aws/awscontext.py
lib/python/treadmill_aws/dnsmonitor.py
lib/python/treadmill_aws/hostmanager.py
lib/python/treadmill_aws/ipaclient.py
lib/python/treadmill_aws/sproc/dnsmonitor.py
tests/dnsmonitor_test.py
tests/ec2client_test.py
tests/ipaclient_test.py

DNS monitor daemon and tests complete. 
This module is intended to work in conjunction with a ZK disk mirror, using zk2fs. 
Example invocation:
python -m treadmill sproc --cell {cellname}  dnsdaemon --no-lock --proid {proid} --root /path/to/zkroot
The invoking user needs valid IPA credentials with the permission to list, add and delete DNS records until we switch to using Treadmill kerberos authentication in place of requests_kerberos in the freeIPA client.

DNS Monitor POC complete

---

lib/python/treadmill_aws/hostmanager.py

Installing ipa_client_install includes the dbus module oddjob-mkhomedir. This module is used when IPA users first log into a new instance. 
On RHEL 7.4, the module fails to start after installation until dbus is restarted. NetworkManager cannot gracefully recover from a dbus restart, so we restart that module as well.

Adding fix for oddjob-mkhomedir error on instance create

---

lib/python/treadmill_aws/ipaclient.py
tests/usermanager_test.py

The IPA client response always contains the key 'error', set by default to None. 
This patch changes the function logic to check the value of the 'error' key instead of checking for the presence of the 'error' key.

Changed logic in IPA client error handling

---

lib/python/treadmill_aws/ipaclient.py
tests/ipaclient_test.py
tests/usermanager_test.py

I've added the searchlimit: 0 (infinite) parameter to the host_find, dnsrecord_find, and user_find functions to prevent the IPA API from truncating results.

Removing IPA search limit for API calls

---

lib/python/treadmill_aws/cli/admin/aws/instance.py

With the argument **default=10**, Click expects an integer and exits with an error if a string is passed instead. 
Changed the default argument to reflect the intent of the callback function & clarified the help text.

Correcting CLI behaviour

---

MANIFEST.in
lib/python/treadmill_aws/bootstrap/master/aws.linux/treadmill/env/TREADMILL_ZOOKEEPER
lib/python/treadmill_aws/bootstrap/master/aws.py
lib/python/treadmill_aws/bootstrap/node/aws.linux/env/TREADMILL_ZOOKEEPER
lib/python/treadmill_aws/plugins/zookeeper.py

- Properly configure zk connection string to use sasl protocol.
- Handle admin/admins role when constructing user acl.
- Added master bootstrap profile.

Fixes for AWS zookeeper.

---

lib/python/treadmill_aws/bootstrap/master/aws.linux/treadmill/env/TREADMILL_ZOOKEEPER
lib/python/treadmill_aws/bootstrap/node/aws.linux/env/TREADMILL_ZOOKEEPER
lib/python/treadmill_aws/bootstrap/node/aws.linux/init/kernel_watchdog.yml

- Zookeeper SASL plugin does not seem to work properly, temporary
disable sasl in connection string.
- Disable kernel watchdog.

Temprorary disable sasl for zk.

---

lib/python/treadmill_aws/bootstrap/node/aws.linux/bin/parts/50_configure_keytabs.sh
lib/python/treadmill_aws/bootstrap/node/aws.linux/bin/parts/60_ld_so_preload.sh

- Prepare host keytab file in the treadmill/spool/keytab directory.
- Ensure that /etc/ld.so.preload exists, as temp workaround until the
code to handle file absense gracefully.

Add boot configuration scripts.

---

lib/python/treadmill_aws/cli/admin/cell.py
lib/python/treadmill_aws/cli/admin/templates/appmonitor
lib/python/treadmill_aws/cli/admin/templates/cellapi
lib/python/treadmill_aws/cli/admin/templates/cellsync
lib/python/treadmill_aws/cli/admin/templates/monitors
lib/python/treadmill_aws/cli/admin/templates/scheduler
lib/python/treadmill_aws/cli/admin/templates/stateapi
lib/python/treadmill_aws/cli/admin/templates/trace-cleanup
lib/python/treadmill_aws/cli/admin/templates/wsapi

- admin cell configure/restart apps/monitors will inclnude scheduler
among other system apps. No need to run separate treadmill master
anymore.

Add "master" apps to admin cell bootstrap.

---

lib/python/treadmill_aws/hostmanager.py
tests/hostmanager_test.py

This change wraps the YAML passed to AWS in single quotes. This is important due to special characters and globs embedded in the OTP.
otp: 123456 
to 
'otp': '123456'

Escaping values in generated YAML

---

lib/python/treadmill_aws/bootstrap/node/aws.linux/etc/pam.d/sshd

New sshd pam config for containers.
This replaces config mounted from underlying host. If pulls in session stack from "password-auth" and replaces pam_oddjob_mkhomedir.so with pam_mkhomedir.so.
pam_oddjob_mkhomedir.so has dependency on dbus socket which it uses to ask sssd to create home directory. This is wrong for many reason (having dbus socket visible in container represents an IPC path to the underlying host, not to mention, homedir would be by sssd on the underlying host.
pam_mkhomedir.so causes homedir to be created in the container itself and has no dependency on dbus or sssd.

sshd pam config - replaces pam_oddjob_mkhomedir.so with pam_mkhomedir.so

---

lib/python/treadmill_aws/bootstrap/aws_aliases.py

There is no need for an AWS specific override.

docker: Leave the integration to Treadmill core

---

entry_points.txt
lib/python/treadmill_aws/cli/admin/krb5keytab.py
lib/python/treadmill_aws/cli/krb5keytab.py
lib/python/treadmill_aws/sproc/krb5keytabproxy.py
tests/sproc/krb5keytabproxy_test.py

- treadmill krb5keytab - request <user>/<host> keytab via local
krb5keytab proxy.
- treadmill admin krb5keytab - request keytab directly from the keytab
server.
- treadmill sproc krb5keytab-proxy - run local proxy as root,
authenticate requests using peercred protocol, forward request to
krb5keytab server.

Implemented krb5keytab support.

---

entry_points.txt
lib/python/treadmill_aws/cli/admin/ipa.py
lib/python/treadmill_aws/cli/krb5keytab.py
lib/python/treadmill_aws/ipaclient.py

- treadmill admin ipa krb5keytab
--add HOST:PORT ...
--remove HOST:PORT ...
TODO: Records are added with default (0) priority and weight. Need
better cleanup to detect records with non-default values if they are
added bypassing the tool.

Admin utility to manage _krb5keytab srv records.

---

lib/python/treadmill_aws/bootstrap/node/aws.linux/env/TREADMILL_ZOOKEEPER
lib/python/treadmill_aws/bootstrap/zookeeper/aws.linux/treadmill/init/zk.yml
lib/python/treadmill_aws/bootstrap/zookeeper/aws.linux/treadmill/zookeeper/conf/jaas.conf
lib/python/treadmill_aws/bootstrap/zookeeper/aws.linux/treadmill/zookeeper/conf/zoo.cfg
lib/python/treadmill_aws/bootstrap/zookeeper/aws.py
lib/python/treadmill_aws/plugins/zookeeper.py
tests/zookeeper_test.py

- Request Zookeeper keytabs on start. It is assumed that
krb5keytab-proxy service is started on the host by systemd.
- Properly construct user/host ACLs, to include full kerberos realm.
TODO: consider alternative configuration, when krb5keytab-proxy is part
of Zookeeper supervision tree.

Add SASL support to Zookeeper bootstrap.

---

lib/python/treadmill_aws/ec2client.py

More user-friendly error messages; currently this outputs an error like the following:
treadmill.exc.NotFoundError: No None found.

Clarified error message

---

lib/python/treadmill_aws/ec2client.py
tests/ec2client_test.py

Changes the default EC2 disk type from magnetic to GP2 (non-provisioned SSD). 
They cost the same amount and have 1/3 to 1/10 the IOPS performance.

Change default instance disk type to SSD

---

lib/python/treadmill_aws/cli/admin/aws/instance.py

If no argument passed, Click will raise a "Missing Argument" error rather than pass an empty list.

Added fix for start/stop instance argument selector

---

lib/python/treadmill_aws/cli/admin/ipa.py
lib/python/treadmill_aws/ipaclient.py

- Fix ipaclient not to append . to hostname when creating srv records.
- Fix cli/admin/ipa not to use dns domain for srv record name, assume
default domain.

Use relative dns names when setting ipa srv recs.

---

entry_points.txt
lib/python/treadmill_aws/cli/admin/cell/docker.py
lib/python/treadmill_aws/cli/admin/cell/image.py
lib/python/treadmill_aws/cli/admin/cell/realm.py
lib/python/treadmill_aws/cli/admin/cell/subnet.py

- treadmill admin aws cell commands:
docker - manage docker registries
subnets - manage list of EC2 subnets for the cell
realm - set cell kerberos realm
image - set default AMI for cell nodes.
The data will be used to automate deployment of cell infrastructure.

Add CLI tools to manage cell data.

---

lib/python/treadmill_aws/bootstrap/openldap/aws.py

This change correctly sets the openldap user to match the user sourced from `treadmill admin install --owner. `

Update openldap bootstrap to use treadmillid as owner

---

lib/python/treadmill_aws/bootstrap/node/aws.linux/init/registry.yml
lib/python/treadmill_aws/cli/admin/cell/configure_data.py
lib/python/treadmill_aws/formatter.py

This sets up an s3-backed Docker registry running in init1 on Treadmill nodes. 
I also added hooks to write the keys S3_DOCKER_BUCKET and S3_REGION to the cell record in LDAP.

Docker registry as init1 service

---

lib/python/treadmill_aws/syscfg.py

os.environ refuses to set null environment variables.

Skip empty environment variables

---

lib/python/treadmill_aws/autoscale.py
lib/python/treadmill_aws/hostmanager.py
tests/hostmanager_test.py

Laying out an expanded tags system. When the PR to make Autoscaler partition aware lands, we should add the partition to this tag list- it can be ingested by the AWS billing system.

Tagging framework

---

lib/python/treadmill_aws/cli/admin/aws/instance.py
lib/python/treadmill_aws/ec2client.py
lib/python/treadmill_aws/hostmanager.py
tests/ec2client_test.py

Spot placement should be an optional attribute, explicitly set as an attribute on cell partitions or set by system processes like Autoscaler that deal with ephemeral servers. If it is the default behavior, we will need to exclude Spot from the infra that is not intended to be ephemeral (i.e. system partitions, zookeepers, LDAP, IPA, DNS, etc) that is managed by Treadmill.

Spot placement should be optional

---

lib/python/treadmill_aws/cli/admin/cell/deploy.py
lib/python/treadmill_aws/hostmanager.py

We need to be able to set instance roles on new ZK and LDAP servers to facilitate the use of EC2 instance profiles.

Added instance role to ZK rotate command

---

lib/python/treadmill_aws/autoscale.py
lib/python/treadmill_aws/sproc/autoscale.py
tests/autoscale_test.py

- Bug in having global idle server tracker resulted in removal of
servers from the tracker when processing different partition.

Fix autoscaler idle tracker for many partitions.

---

lib/python/treadmill_aws/cli/admin/krb5keytab.py
lib/python/treadmill_aws/features/krb5keytab.py

To avoid race condition when multiple containers on the same host
request same keytab from IPA, serialize krb5keytab requests and use
local cache. If the keytab is available locally, use it.
TODO: Possible enhancement - check keytab validity (need to establish
sec context to validate that keytab version is current.)

Lock & cache keytabs requested from IPA.

---

lib/python/treadmill_aws/ipa525.py

this is in prep for eliminating user passwords.
after ipa user-add, no need to create password (via ipa cli) or create random key (via kadmin.local), as long as user is using cloudshell/ipa525 to obtain TGT.

ipa525 - create random key for user if user has no keys
