- lib/python/Treadmill_AWS.egg-info/PKG-INFO
- lib/python/Treadmill_AWS.egg-info/entry_points.txt
- lib/python/treadmill_aws/api/host.py
- lib/python/treadmill_aws/aws/manager.py
- lib/python/treadmill_aws/aws/server/awsclient.py
- lib/python/treadmill_aws/aws/server/ipaclient.py
- lib/python/treadmill_aws/cli/admin/aws.py
- tests/aws/__init__.py
- tests/aws/awsclient_test.py
CLI functioning, AWSClient tests complete. IPAClient and CLI tests coming tomorrow.
> AWS Host Manager POC complete

- lib/python/Treadmill_AWS.egg-info/entry_points.txt
- lib/python/treadmill_aws/aws.py
- lib/python/treadmill_aws/cli/admin/aws/image.py
- lib/python/treadmill_aws/cli/admin/aws/secgroup.py
- lib/python/treadmill_aws/cli/admin/aws/subnet.py
- lib/python/treadmill_aws/cli/options.py
- lib/python/treadmill_aws/ec2client.py
- lib/python/treadmill_aws/formatter.py
- lib/python/treadmill_aws/metadata.py
- tests/cli/options_test.py
- Implemented options decorator for handling common selections for
image, subnet, security group and other AWS resources.
- Implemented metadata wrapper for easy access to instance metadata.
- Added "admin aws image configure", improved image pretty formatter.
> Rationalized CLI options for various aws resources.

- requirements.txt
- Point them back to main repo.
> Regression in requirements.txt

- lib/python/treadmill_aws/api/host.py
- lib/python/treadmill_aws/cli/admin/aws/instance.py
- lib/python/treadmill_aws/hostmanager.py
Added ability to import k:v pairs on disk to instance cloud-init data.
> Added import of additional cloud-init variables

- lib/python/treadmill_aws/syscfg.py
- Running syscfg exec -- ... will read treadmill_ environment from
userdata and exec into command.
> Add exec subcommand to syscfg.

- lib/python/treadmill_aws/cli/admin/cell.py
- lib/python/treadmill_aws/cli/admin/templates/adminapi
- lib/python/treadmill_aws/cli/admin/templates/monitors
Add admin api manifest template and add adminapi to the list of system
apps.
> Enable treadmill admin api.

- lib/python/treadmill_aws/dns_sync.py
- do not use treadmill dns zone, it is implied (otherwise records are
created with dns domain concatenated.)
- remove stale srv records pointing to hosts no longer in DNS.
> Corrected dns_sync to create proper srv records:

- lib/python/treadmill_aws/cli/admin/aws/image.py
- lib/python/treadmill_aws/cli/admin/aws/instance.py
- lib/python/treadmill_aws/ec2client.py
- lib/python/treadmill_aws/hostmanager.py
Code refactoring:
Added set instance eni feature
Added set instance ip address feature
Changed image ssh key dependency from True to False
> set-ip-eni-sshkey

- lib/python/treadmill_aws/ipaclient.py
- lib/python/treadmill_aws/noproxy.py
- lib/python/treadmill_aws/syscfg.py
- Created a special resource mgr to disable proxy in a safe was. TODO:
move to treadmill-core.
> Disable proxy when reading userdata with syscfg.

- entry_points.txt
- lib/python/treadmill_aws/cli/admin/aws/user.py
- lib/python/treadmill_aws/formatter.py
- lib/python/treadmill_aws/usermanager.py
- tests/usermanager_test.py
- Manage IPA users separately from IAM users.
> Split user management into IPA/IAM.

- entry_points.txt
- lib/python/treadmill_aws/features/krb5keytab.py
- Specifying feature: krb5keytab will configure system app to call
krb5keytab daemon on IPA server.
> Added krb5keytab feature.

- lib/python/treadmill_aws/hostmanager.py
- tests/hostmanager_test.py
- Fix base N conversion of timestamp to be lexically ordered.
> Fixed hostname generation to be ordered.

- entry_points.txt
- lib/python/treadmill_aws/cli/admin/cell/disksize.py
- lib/python/treadmill_aws/cli/admin/cell/hostgroup.py
- lib/python/treadmill_aws/cli/admin/cell/instanceprofile.py
- lib/python/treadmill_aws/cli/admin/cell/size.py
- CLI to set cell attributes:
* disk size
* hostgroup
* instanceprofile
* size
> Added support for cell (instance) attributes.

- lib/python/treadmill_aws/cli/admin/cell/nodes.py
- Allow image name (not image id) in treadmill cell data.
- Fix default for partition.
> Allow image name in treadmill cell metadata.

- lib/python/treadmill_aws/autoscale.py
- lib/python/treadmill_aws/cli/admin/cell/nodes.py
- Move create/delete servers in the cell to separate module.
> Implemented separate autoscale module.

- entry_points.txt
- lib/python/treadmill_aws/autoscale.py
- lib/python/treadmill_aws/cli/admin/cell/nodes.py
- lib/python/treadmill_aws/hostmanager.py
- lib/python/treadmill_aws/sproc/autoscale.py
- tests/autoscale_test.py
- Supports max/min servers.
- Will increment server count at most batch count.
- Limitation - does not support partitions yet, operates on default
partition.
> Simple autoscaler for treadmill cell.

- lib/python/treadmill_aws/cloudshell.py
- Rather than -c "command", use -- <args> syntax.
> Change cloudshell login cli.

- lib/python/treadmill_aws/api/host.py
- lib/python/treadmill_aws/autoscale.py
- lib/python/treadmill_aws/cli/admin/aws/instance.py
- lib/python/treadmill_aws/hostmanager.py
- tests/hostmanager_test.py
> Handle address/EC2 instance exhaustion, break instance delete into batches

- tests/hostmanager_test.py
> Mocking AWS account name

- lib/python/treadmill_aws/awscredential.py
- lib/python/treadmill_aws/sproc/awscredential.py
* added logging throughout processing of request
* removed --account-id option, this can be determined programatically
* removed --admin-group, this is an undesirable feature
> improved logging, removed undesirable sproc cli options

- lib/python/treadmill_aws/autoscale.py
- lib/python/treadmill_aws/cli/admin/cell/configure_partition.py
- lib/python/treadmill_aws/formatter.py
We can use this to customize attributes like instance size or type per partition.
> Added partition-level override to cell data

- lib/python/treadmill_aws/hostmanager.py
- lib/python/treadmill_aws/ipaclient.py
Fixing edge case where invalid PTR record needed to be cleaned up.
> Update hostmanager to handle bad PTR records

- entry_points.txt
- lib/python/treadmill_aws/cli/admin/cell/configure_dns.py
- lib/python/treadmill_aws/cli/admin/ipa.py
- lib/python/treadmill_aws/dns_sync.py
- lib/python/treadmill_aws/garbage_collector.py
- lib/python/treadmill_aws/hostmanager.py
- lib/python/treadmill_aws/ipaclient.py
- lib/python/treadmill_aws/sproc/garbage_collector.py
- lib/python/treadmill_aws/usermanager.py
- tests/hostmanager_test.py
- tests/ipaclient_test.py
- Refactored garbage collector, error handling.
- Rewritten IPAClient (consistent method names, arguments, result).
> - DNS garbage collection plugin.

- entry_points.txt
- lib/python/treadmill_aws/cli/admin/aws/__init__.py
- lib/python/treadmill_aws/cli/admin/aws/image.py
- lib/python/treadmill_aws/cli/admin/aws/policy.py
- lib/python/treadmill_aws/cli/admin/aws/role.py
- lib/python/treadmill_aws/cli/admin/aws/user.py
- lib/python/treadmill_aws/formatter.py
* treadmill admin aws policy - new
* treadmill admin aws role - support for trusted users
* treadmill admin aws user - cosmetic fixes
> treadmill admin aws user,role,policy updates

- lib/python/treadmill_aws/cli/admin/aws/role.py
- lib/python/treadmill_aws/formatter.py
* treadmill admin aws role configure cli options and corresponding
output (formatter) are now more consistent with each other
> treadmill admin aws role enhancements
